### ISSUE TITLE
blibs a librarypath

### ISSUE THREAD

**Issue by zbyti** [atarionline/starekino#11]
W obecnym `wsk.pas` widzę:

```
{$librarypath '../../blibs/'}
{$librarypath '../../MADS/blibs/'}
```
Sądzę, że to utrudnia kolaborację. Jeżeli ktoś z jakiegoś powodu ma Mad Pascala w systemie ustawionego tak, że podczas kompilacji nie widzi dystrybuowanych z MP blibsów to w dowolnym ze znanych mi dziś OS można zrobić sobie link symboliczny (tak, Windows też to potrafi).

Ja blibsy i swoje biblioteki w projekcie mam po prostu dołączone:

```
{$librarypath 'blibs'}
{$librarypath 'zlibs'}
{$librarypath 'benchmarks'}
```
gdzie blibs jest w katalogu MP tak jak jest dostarczany.

**Comment by MADRAFi** [comment]
no nie do konca. Taka deklaracja oznacza ze w katalogu bierzacym uzywasz biblioteki z katalogu blibs.
Mi latwiej jest dodac kolejny librarypath pod windows niz tworzyc hard linki

**Comment by zbyti** [comment]
Co prawda nie rozumiem co w takim razie jest katalogiem bieżącym u mnie ale ok, no i raczej miałem na myśli soft link a nie hard link - tak dla bezpieczeństwa

**Comment by zbyti** [comment]
https://github.com/zbyti/a8-mad-pascal-bench-suite blibsy są w katalogu z Mad Pascalem i nic nie musiałem kombinować. Nie u każdego nawet relatywna ścieżka będzie na miejscu, linku symbolicznego też nie mam w katalogu projektu po prostu kompilator startuje z miejsca w którym ma dostęp do blibs.

```
#!/bin/bash

mp="$HOME/Programs/MadPascal/mp"
mads="$HOME/Programs/mads/mads"
base="$HOME/Programs/MadPascal/base"
name="wsk"

$mp $name.pas -o

if [ -f $name.a65 ]; then
  [ ! -d "output" ] && mkdir output
  mv $name.a65 output/
  $mads output/$name.a65 -x -i:$base -o:output/$name.xex
else
  exit 1
fi
```

**Comment by zbyti** [comment]
```
mp="$HOME/Programs/MadPascal/mp"
mads="$HOME/Programs/mads/mads"
base="$HOME/Programs/MadPascal/base"
```
ten fragment można znormalizować lub każdy z unixopodobnym systemem może zrobić go pod siebie i nie będziemy commitować swoich zmian w nim.

ostatecznie niech każdy obecną swoją metodę zmodyfikuje tak by **mp** był uruchamiany ze swojego HOME to będzie widział blibsy bez żadnych cyrkowych sztuczek ;)

**Comment by MADRAFi** [comment]
Ja bym prosil o nie usuwanie libpath z kodu.
Z tego co zauwazylem moze byc wiele dodanych sciezek i nie tworzy to problemu przy kompilacji.
Teraz po commit nie moge skompilowac.

**Comment by zbyti** [comment]
No to jakbym chciał dołączyć do projekty mam dołożyć swoją trzecią? Lepiej wypracujmy jedno podejście.

Dobrze, nie narzucam się ale prosiłbym o rozwagę ;)
